architecture:
  next:
    - coding
  agent_config: architecture.yaml
  agent:
    name: LLMAgent
    kwargs:
      tag: Architecture


coding:
  next:
    - refine
  agent_config: coding.yaml
  agent:
    name: LLMAgent
    kwargs:
      tag: Coding

refine:
  agent:
    name: LLMAgent
    kwargs:
      tag: Refiner