
name: Bug report
title: "[<Agent component: framework|tool|llm|etc...>] "
description: Problems and issues with code of MS-Agent
labels: [bug]
assignees:
  - wangxingjun778
  - tastelikefeet
  - suluyana
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting the problem!
        Please make sure what you are reporting is a bug with reproducible steps. To ask questions
        or share ideas, please post on our [Discussion page](https://github.com/modelscope/ms-agent/discussions) instead.

  - type: checkboxes
    id: checks
    attributes:
      label: Initial Checks
      description: |
        Just a few checks to make sure you need to create a bug report.
      options:
        - label: I have searched related issues and docs but cannot get the expected help.
          required: false
        - label: The bug has not been fixed in the latest version.
          required: false

  - type: textarea
    attributes:
      label: A clear and concise description of what the bug is.
      description: ''
      placeholder: >
        To help us understand the issue better, please provide the following:

        - What command or script did you run?
        - What happened? What did you expect to happen?
        - If there are any error messages, please copy and paste the exact log output (no screenshots).
    validations:
      required: true

  - type: textarea
    attributes:
      label: Versions / Dependencies
      description: Please specify the versions of MS-Agent, Python, OS, and other libraries that are used.
      placeholder: >
        Please specify the versions of dependencies.
    validations:
      required: true
