name: Feature Request
description: Suggest an idea for MS-Agent project
title: "[<Agent component: framework|tool|llm|etc...>] "
labels: [enhancement]
assignees:
  - wangxingjun778
  - tastelikefeet
  - suluyana

body:
  - type: markdown
    attributes:
      value: |
        Thank you for finding the time to propose a new feature!
        We really appreciate the community efforts to improve MS-Agent.

  - type: textarea
    attributes:
      label: Description
      description: A description of your feature, meanwhile please attach any links/papers related to the feature.
